version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    image: ${DOCKERHUB_USERNAME}/resume-tracker:latest
    container_name: flask-api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_NAME}
    ports:
      - "5000:5000"

volumes:
  postgres_data:
