name: CD Resume App

on:
  workflow_run:
    workflows:
      - "CI Resume App"
    types:
      - completed
    branches:
      - local-mini-pc

jobs:
    
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:

      - name: Set deployment version
        run: |
          FULL_SHA="${{ github.event.workflow_run.head_sha }}"
          SHORT_SHA="${FULL_SHA:0:7}"
          echo "SHORT_SHA=$SHORT_SHA" >> "$GITHUB_ENV"

      - name: Show deployment version
        run: |
          echo "Deploying image tag: $SHORT_SHA"
    
      - name: Pull application image on app server
        run: |
          ssh -i ~/.ssh/deploy_vm_resume \
          deploy@${{ secrets.APP_VM_IP }} \
          "docker pull ${{ secrets.DOCKERHUB_USERNAME }}/resume-tracker:${SHORT_SHA}"

      - name: Verify application image
        run: |
          ssh -i ~/.ssh/deploy_vm_resume \
          deploy@${{ secrets.APP_VM_IP }} \
          "docker image ls ${{ secrets.DOCKERHUB_USERNAME }}/resume-tracker"

      - name: Deploy application
        run: |
          ssh -i ~/.ssh/deploy_vm_resume \
          deploy@${{ secrets.APP_VM_IP }} \
          "cd ~/devops-lab-2026/ && \
          DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} \
          IMAGE_TAG=${SHORT_SHA} \
          docker compose up -d web"

      - name: Verify deployment
        run: |
          ssh -i ~/.ssh/deploy_vm_resume \
          deploy@${{ secrets.APP_VM_IP }} \
          "curl --fail http://localhost:5000/health"

      - name: Verify deployed image
        run: |
          ssh -i ~/.ssh/deploy_vm_resume \
          deploy@${{ secrets.APP_VM_IP }} \
          "docker inspect flask-api --format='{{.Config.Image}}'"
