name: CD Resume App

on:
  push:
    branches:
      - local-mini-pc

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Verify self-hosted runner
        run: |
          hostname
          whoami
          uname -m

      - name: Verify ssh connection to the host server
        run: |
          ssh -i ~/.ssh/deploy_vm_resume deploy@${{ secrets.APP_VM_IP }} hostname
          ssh -i ~/.ssh/deploy_vm_resume deploy@${{ secrets.APP_VM_IP }} docker ps
