name: CI/CD  Resume App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKERN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
         context: .
         platforms: linux/arm64
         push: true
         tags: ${{ secrets.DOCKERHUB_USERNAME }}/resume-tracker:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Connect to Tailscale
        run: |
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Deploy
        run: |
          ssh -i ~/.ssh/id_ed25519 \
          -o StrictHostKeyChecking=no \
          -p 2222 \
          ${{ secrets.SERVER_USER }}@${{secrets.SERVER_IP}} "
           cd ~/flask-app &&
           docker pull ${{ secrets.DOCKERHUB_USERNAME }}/resume-tracker:latest &&
           docker compose down &&
           docker compose up -d
          "
